config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  mount ActionCable.server => '/cable'

  root to: 'homes#show'

  # resource :workshop
  # resource :server_data, only: [:show] do
  # end
  resource :home, only: [:show]
  resources :users, only: [:show] do
    resource :regenerate_api_token, module: :users, only: [:new, :create]
  end
  resources :client_apps do
    resource :source, module: :client_apps, only: [:show, :edit, :update]
    resource :fork, module: :client_apps, only: [:new, :create]
    resource :serve, module: :client_apps, only: [:show]
    post :reorder, on: :collection
  end
  resources :servers, only: [:index]
  namespace :servers do
    namespace :chat_studio do
      resource :home, only: [ :show ]
      resources :rooms, only: [ :new, :create ]
      resources :messages, only: [ :new, :create ]
      resource :events, only: [ :show ]
      namespace :api do
        namespace :v0 do
          resource :user, only: [ :show ]
          resources :rooms, only: [:index, :show, :create]
          resources :messages, only: [ :show, :create ]
          resource :events, only: [ :show ]
        end
      end
    end
  end
  resource :fake_post, only: [ :create ]

end

app/models/client_app.rb
class ClientApp < ApplicationRecord

  belongs_to :user

  scope :published, -> { where(published: true).sort_by { |client_app| client_app.sort_order || 0 }.sort_by { |client_app| client_app.user.username == 'lachlan' ? 1 : 2 } }
  scope :sorted, -> { all.sort_by { |client_app| client_app.sort_order || 0 } }

end

app/controllers/client_apps/forks_controller.rb
module ClientApps

  class ForksController < ApplicationController

    def new
      @client_app = ( current_user.client_apps.find(params[:client_app_id]) || ClientApp.where(id: params[:client_app_id]).published.first).dup
    end

    def create
      @client_app = ( current_user.client_apps.find(params[:client_app_id]) || ClientApp.where(id: params[:client_app_id]).published.first).dup
      sort_order = current_user.client_apps.sorted.first.sort_order - 1
      @client_app.assign_attributes(strong_params.merge({ published: false, sort_order: sort_order }))
      if @client_app.save
        render
      else
        render :new
      end
    end

    private

    def strong_params
      params.require(:client_app).permit(:name)
    end

  end

end

app/controllers/client_apps/serves_controller.rb
module ClientApps

  class ServesController < ApplicationController

    skip_before_filter :verify_authenticity_token, only: [:create]

    def show
      @client_app = current_user.client_apps.find(params[:client_app_id]) || ClientApp.where(id: params[:client_app_id]).published.first
      render html: @client_app.source.to_s.gsub('__API_TOKEN__', current_user.api_token).html_safe
    end

  end

end

app/controllers/client_apps/sources_controller.rb
module ClientApps

  class SourcesController < ApplicationController

    def show
      @client_app = current_user.client_apps.find(params[:client_app_id]) || ClientApp.where(id: params[:client_app_id]).published.first
    end

    def edit
      @client_app = current_user.client_apps.find( params[:client_app_id] )
    end

    def update
      @client_app = current_user.client_apps.find( params[:client_app_id] )
      if @client_app.update(strong_params)
        render
      else
        render :edit
      end
    end

    private

    def strong_params
      params.require(:client_app).permit(:source)
    end

  end

end

app/controllers/client_apps_controller.rb
class ClientAppsController < ApplicationController

  def index
    # @client_apps = current_user.client_apps.sorted
    # byebug
  end

  def show
    @client_app = current_user.client_apps.find( params[:id] )
  end

  def new
    @client_app = current_user.client_apps.build
  end

  def create
    @client_app = current_user.client_apps.build(strong_params)
    sort_order = current_user.client_apps.sorted.first.sort_order - 1
    @client_app.assign_attributes(sort_order: sort_order)
    if @client_app.save
      redirect_to action: 'show', id: @client_app.id
    else
      render :new
    end
  end

  def edit
    @client_app = current_user.client_apps.find( params[:id] )
  end

  def update
    @client_app = current_user.client_apps.find( params[:id] )
    if @client_app.update(strong_params.merge({user_id: current_user.id}))
      redirect_to action: 'show'
    else
      render :edit
    end
  end

  def destroy
    @client_app = current_user.client_apps.find( params[:id] )
    @client_app.destroy
    redirect_to client_apps_path
  end

  def reorder
    reorder_strong_params[:client_apps_attributes].each do |n, client_app|
      # byebug
      @client_app = current_user.client_apps.find( client_app[:id] )
      @client_app.update(sort_order: client_app[:sort_order])
    end
    head :ok
  end

  private

  def strong_params
    params.require(:client_app).permit(:name, :description, :published)
  end

  def reorder_strong_params
    params.require(:user).permit(client_apps_attributes: [ :id, :sort_order ])
  end

end

app/views/client_apps/_form.html.erb
<%= simple_form_for @client_app do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :published %>
  <%= f.button :submit %>
<% end %>

app/views/client_apps/edit.js.erb
$(".modal").modal("hide");
$("body").append(
  "<%= j modal( icon_text( 'Edit client app', 'fa-edit' ), render( 'client_apps/form' ) ) %>"
);
$(".modal").on("hidden.bs.modal", function(){$(this).remove();});
$(".modal").modal("show");

app/views/client_apps/index.html.erb
<script>
  function clientAppAllowDrop(ev) {
      ev.preventDefault();
  };

  function clientAppDrag(ev) {
    ev.dataTransfer.setData("text", ev.target.closest('.drag_to_sort').id);
  };

  function clientAppDrop(ev) {
    ev.preventDefault();
    var data = ev.dataTransfer.getData("text");

    var target = ev.target.closest('.drag_to_sort');
    var dragged = $("#" + data)[0];

    if ( target != dragged ) {
      var targetInput = $(target).find('input');
      var draggedInput = $(dragged).find('input');

      dragged.remove();
      target.parentElement.insertBefore(dragged, target);

      var form = $("#drag_to_sort_client_apps_form");
      var sortOrderInputs = form.find(".drag_to_sort .user_client_apps_sort_order input");
      sortOrderInputs.each( function( i ) { $(this).val(i); })

      form.find("input[name='commit']").click();
    };
  };
</script>

<%= link_to icon_text("App library", 'fa-play'),
root_path, class: 'btn btn-lg pull-right' %>

<%= link_to icon_text("New app", 'fa-plus'),
new_client_app_path, class: 'btn btn-lg pull-right', remote: true %><br>

<%= simple_form_for current_user, html: { id: "drag_to_sort_client_apps_form" }, url: reorder_client_apps_path(), method: :post, remote: true do |f| %>
  <%= f.simple_fields_for :client_apps, f.object.client_apps.sorted do |ff| %>
    <%= content_tag :div,
    class: 'drag_to_sort',
    'data-client_app_id': ff.object.id,
    id: "client_app_#{ff.object.id}",
    draggable: :draggable,
    ondragover: "clientAppAllowDrop(event)",
    ondrop: "clientAppDrop(event)",
    ondragstart: "clientAppDrag(event)" do %>
    <%= ff.input :id, as: :hidden %>
    <%= ff.input :sort_order, as: :hidden %>
      <%= link_to ( ff.object.published ?
        icon_text(ff.object.name, 'fa-caret-right') :
        icon_text(ff.object.name, 'fa-angle-right')
      ), ff.object,
      class: 'btn btn-lg' %>
    <% end %>
  <% end %>
  <div style="display: none;"><%= f.submit %></div>
<% end %>

app/views/client_apps/show.html.erb
<%= link_to( icon_text(false, "fa-arrow-up"), client_apps_path() + "#client_app_#{@client_app.id}", class: "btn btn-lg" ) %>
<%= link_to(icon_text("Fork", 'fa-code-fork'), new_client_app_fork_path(@client_app), class: 'btn btn-lg', remote: true) %>
<%= link_to( icon_text("Edit", "fa-edit"), edit_client_app_path(@client_app.id), class: "btn btn-lg", remote: true ) %>
<%= link_to( icon_text("Delete", "fa-trash-o"), client_app_path(@client_app.id), method: :DELETE, class: "btn btn-lg pull-right", data: { confirm: "Are you sure that you want to delete this app?"}, remote: true ) %><br>
<h3><%= @client_app.name %></h3>
<p class="clearfix">
  <%= @client_app.description %>
  <small class="pull-right"><%= @client_app.published ? 'Published' : 'Unpublished' %></small>
</p>
<hr>
<div class="clearfix">
  <%= link_to( icon_text("Run", "fa-play"), client_app_serve_path(@client_app.id), class: "btn btn-lg pull-right", target: ( "_EnginepadApp_" + @client_app.id.to_s )  ) %>
  <%= link_to( icon_text("Code", "fa-keyboard-o"), edit_client_app_source_path(@client_app.id), class: "btn btn-lg" ) %>
</div>
<pre><%= @client_app.source %></pre>