scrapheap/server/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  mount ActionCable.server => '/cable'

  root to: 'homes#show'

  resource :workshop
  resource :server_data, only: [:show] do
    resources :rooms, module: :server_data, only: [:new, :create ]
    resources :messages, module: :server_data, only: [:new, :create ]
    resource :events, module: :server_data, only: [:show ]
  end
  resources :users, only: [:show]
  resources :client_apps do
    resource :source, module: :client_apps, only: [:edit, :update]
    resource :serve, module: :client_apps, only: [:show]
  end
  resource :home, only: [:show]
  resource :fake_post, only: [:create]
  namespace :api do
    namespace :v0 do
      resources :rooms, only: [:index, :show, :create]
      resources :messages, only: [:show, :create]
      resource :events, only: [:show ]
    end
  end

end

scrapheap/server/app/controllers/server_data/messages_controller.rb
module ServerData
  class MessagesController < ApplicationController

    # include ActionController::Live

    def new
      @message = Message.new
    end

    def create
      @message = Message.new(strong_params.merge({user_id: current_user.id}))
      if @message.save
        render
      else
        render :new
      end
    end

    private

    def strong_params
      params.require(:message).permit(:room_id, :body)
    end

  end

end

scrapheap/server/app/controllers/server_data/rooms_controller.rb
module ServerData
  class RoomsController < ApplicationController

    # include ActionController::Live

    def new
      @room = Room.new
    end

    def create
      @room = Room.new(strong_params.merge({user_id: current_user.id}))
      if @room.save
        render
      else
        render :new
      end
    end

    private

    def strong_params
      params.require(:room).permit(:name)
    end

  end

end

scrapheap/server/app/controllers/server_data_controller.rb
class ServerDataController < ApplicationController

  def show
    # @rooms = Room.all
  end

  # def new_message
  #   @message = Message.new
  # end

end

scrapheap/server/app/views/server_data/show.html.erb
<div class="clearfix">
<%= link_to(rails_admin_path, class: "btn btn-lg pull-right") do
    icon_text('DB admin', 'fa-database')
  end %>
</div>

<div class="row">
  <div class="col-sm-6">
    <legend>Rooms</legend>
    <h5>Index</h5>
    <p><code>GET /api/v0/rooms</code> returns list of rooms as json.</p>
    <p><%= link_to(icon_text('Open room index','fa-external-link'), '/api/v0/rooms', class: "btn btn-lg", target: '_blank') %></p>
    <hr>
    <h5>Create</h5>
    <p><code>POST /api/v0/rooms</code> with parameter <code>room[name]</code> to create a room.</p>
    <%= link_to(icon_text('New room form', 'fa-plus'), '/server_data/rooms/new', class: "btn btn-lg", remote: true ) %>
    <hr>
    <h5>Read</h5>
    <p><code>GET /api/v0/rooms/#id</code> returns room by ID, with messages, as json.</p>
    <p>For example, find room #1 at <code>/api/v0/rooms/1</code>.</p>
    <p><%= link_to(icon_text('Open room 1','fa-external-link'), "/api/v0/rooms/1", class: "btn btn-lg", target: '_blank') %></p>
    <hr>
    <h5>Update</h5>
    <p><code>POST /api/v0/rooms/#id</code> with parameter <code>room[name]</code> to update a room.</p>
    <p>A room can be updated (i.e. renamed) by the user that created it.</p>
    <hr>
    <h5>Delete</h5>
    <p><code>DELETE /api/v0/rooms/#id</code> to delete a room.</p>
    <p>A room can be deleted by the user that created it.</p>
    <p>When a room is deleted its associated messages will be deleted too.</p>
    <hr>
  </div>

  <div class="col-sm-6">
    <legend>Messages</legend>
    <h5>Create</h5>
    <p><code>POST /api/v0/messages</code> with parameters <code>message[room_id], message[body]</code> to create a message.</p>
    <%= link_to(icon_text('New message form', 'fa-plus'), '/server_data/messages/new', class: "btn btn-lg", remote: true ) %>
    <hr>
    <h5>Events</h5>
    <p><code>GET /api/v0/events</code> returns a text stream of new messages.</p>
    <%= link_to( nil, id: 'start_events_button', class: "btn btn-lg" ) { icon_text('Start', 'fa-play') } %>
    <%= link_to( nil, id: 'stop_events_button', class: "btn btn-lg", style: "display: none;" ) { icon_text('Stop', 'fa-spinner fa-spin') } %>
    <pre id="server_events"></pre>
    <hr>
  </div>
</div>